### ISSUE TITLE
Error when trying to upload empty file

### ISSUE THREAD

**Issue by JosielFaleiros** [web-2-utfpr/instaclone#25]
![image](https://user-images.githubusercontent.com/14371477/38710832-98111800-3e98-11e8-9302-32b58dec6948.png)

When I do click on the button "Postar" without a image selected, appears this error.

**Comment by STHGM** [comment]
Issue Solved properly. The field now pops up an notification if no image is trying to be uploaded.

**Comment by JosielFaleiros** [comment]
here the problem persists, the error is not in the website because @rafaelnsantos is testing another branch online, I am reopening because the error persists.

**Comment by JosielFaleiros** [comment]
https://github.com/web-2-utfpr/instaclone/pull/41
