### ISSUE TITLE
Problem when adding a new Servlet

### ISSUE THREAD

**Issue by LucasSantosJr** [web-2-utfpr/instaclone#35]
Galera, eu adicionei uma classe no pacote Servlet com tudo configurado, mas o servidor não encontra a rota.

```Java
@WebServlet(
        name = "Log",
        urlPatterns = {"/log"}
)
public class LogoutServlet extends HttpServlet {
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp)
            throws ServletException, IOException {
        req.getSession().invalidate();
        resp.sendRedirect("login");
    }
}
```

**Comment by rafaelnsantos** [comment]
muda o nome do HttpServletResponse res para resp

**Comment by LucasSantosJr** [comment]
Foi na hora de adicionar o exemplo que eu mudei, mas no código estão iguais. A IDE ia apontar esse erro.

**Comment by JosielFaleiros** [comment]
@LucasSantosJr Executando sua branch, não constatei nenhum erro.
https://github.com/web-2-utfpr/instaclone/blob/logout/src/main/java/servlet/LogoutServlet.java

![image](https://user-images.githubusercontent.com/14371477/38745091-fbedd710-3f19-11e8-8fb2-cbf33518521f.png)

quando acesso a rota /log sou redirecionado para /login como esperado pelo código.
