### ISSUE TITLE
Login button is displaying kind of weird

### ISSUE THREAD

**Issue by LucasSantosJr** [web-2-utfpr/instaclone#37]
![screenshot-2018-4-13 inst4gram homepage](https://user-images.githubusercontent.com/37117794/38753368-81dc9a4a-3f34-11e8-8f45-2e3186e7fde8.png)

**Comment by STHGM** [comment]
I couldn`t replicate the bug. Can you show step-by-step how you got it?

**Comment by JosielFaleiros** [comment]
I think someone forgot to close it
