### ISSUE TITLE
feature sign in

### ISSUE THREAD

**Issue by LucasSantosJr** [web-2-utfpr/instaclone#9]
The user will hit the path `/` and if he are not logged he will have the options _sign in_ and _sign up_.

If he already have an account he may insert your _emai_l and _password_ and in cases if it's right he will be redirect to the `/profile` path.

**Comment by rafaelnsantos** [comment]
http://met.guc.edu.eg/OnlineTutorials/JSP%20-%20Servlets/Full%20Login%20Example.aspx

**Comment by STHGM** [comment]
Issue working properly acording to some tests.
